In [1]:
import pandas as pd

In [2]:
gardiner_df = pd.read_csv("./data/202305_gardiner_flow_data.csv.zip")
weather_df = pd.read_csv("./data/202305_weather_data.csv.zip")

In [3]:
gardiner_df.collectedAt = pd.to_datetime(gardiner_df.collectedAt, utc=True)
gardiner_df.collectedAt = gardiner_df.collectedAt.dt.floor(freq="t")
weather_df.collectedAt = pd.to_datetime(weather_df.collectedAt, utc=True)
weather_df.collectedAt = weather_df.collectedAt.dt.floor(freq="t")

In [4]:
df = gardiner_df.merge(weather_df,on="collectedAt",how="inner")
df

,currentSpeed,collectedAt,visibility,temperature,FeelsLike,humidity,windSpeed,windDegree,cloudsAll,rain1h,snow1h,cloudy,clear,atmosphere,snowy,rainy
0,86,2023-05-01 00:00:00+00:00,10.0,9.19,6.73,90,4.63,290,100,0.0,0,1,0,0,0,0
1,92,2023-05-01 00:05:00+00:00,10.0,9.12,6.64,90,4.63,290,100,0.0,0,1,0,0,0,0
2,92,2023-05-01 00:10:00+00:00,10.0,9.12,6.64,90,4.63,290,100,0.0,0,1,0,0,0,0
3,92,2023-05-01 00:15:00+00:00,10.0,9.13,6.65,90,4.63,290,100,0.0,0,1,0,0,0,0
4,92,2023-05-01 00:20:00+00:00,10.0,9.24,6.22,89,6.17,300,100,0.0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8922,73,2023-05-31 23:35:00+00:00,10.0,28.05,27.51,37,0.89,119,32,0.0,0,1,0,0,0,0
8923,78,2023-05-31 23:40:00+00:00,10.0,27.17,27.04,41,1.54,260,0,0.0,0,0,1,0,0,0
8924,78,2023-05-31 23:45:00+00:00,10.0,27.12,27.00,41,1.54,260,0,0.0,0,0,1,0,0,0
8925,78,2023-05-31 23:50:00+00:00,10.0,26.77,26.79,42,1.54,260,0,0.0,0,0,1,0,0,0
8926,81,2023-05-31 23:55:00+00:00,10.0,26.67,26.72,42,1.54,260,0,0.0,0,0,1,0,0,0

In [5]:
df["Month"] = df.collectedAt.dt.month_name()
df["Weekday"] = df.collectedAt.dt.day_name()
df["Hour"] = df.collectedAt.dt.hour
df["Minute"] = df.collectedAt.dt.minute
df.drop(["collectedAt", "windDegree"],inplace=True,axis=1)
df

,currentSpeed,visibility,temperature,FeelsLike,humidity,windSpeed,cloudsAll,rain1h,snow1h,cloudy,clear,atmosphere,snowy,rainy,Month,Weekday,Hour,Minute
0,86,10.0,9.19,6.73,90,4.63,100,0.0,0,1,0,0,0,0,May,Monday,0,0
1,92,10.0,9.12,6.64,90,4.63,100,0.0,0,1,0,0,0,0,May,Monday,0,5
2,92,10.0,9.12,6.64,90,4.63,100,0.0,0,1,0,0,0,0,May,Monday,0,10
3,92,10.0,9.13,6.65,90,4.63,100,0.0,0,1,0,0,0,0,May,Monday,0,15
4,92,10.0,9.24,6.22,89,6.17,100,0.0,0,1,0,0,0,0,May,Monday,0,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8922,73,10.0,28.05,27.51,37,0.89,32,0.0,0,1,0,0,0,0,May,Wednesday,23,35
8923,78,10.0,27.17,27.04,41,1.54,0,0.0,0,0,1,0,0,0,May,Wednesday,23,40
8924,78,10.0,27.12,27.00,41,1.54,0,0.0,0,0,1,0,0,0,May,Wednesday,23,45
8925,78,10.0,26.77,26.79,42,1.54,0,0.0,0,0,1,0,0,0,May,Wednesday,23,50
8926,81,10.0,26.67,26.72,42,1.54,0,0.0,0,0,1,0,0,0,May,Wednesday,23,55

In [6]:
categorical_attrs = ["Month", "Weekday"]

transformed_df = pd.get_dummies(df, columns=categorical_attrs, prefix="", prefix_sep="")
transformed_df = transformed_df.astype("float32")
transformed_df

,currentSpeed,visibility,temperature,FeelsLike,humidity,windSpeed,cloudsAll,rain1h,snow1h,cloudy,...,Hour,Minute,May,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday
0,86.0,10.0,9.190000,6.730000,90.0,4.63,100.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,92.0,10.0,9.120000,6.640000,90.0,4.63,100.0,0.0,0.0,1.0,...,0.0,5.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,92.0,10.0,9.120000,6.640000,90.0,4.63,100.0,0.0,0.0,1.0,...,0.0,10.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,92.0,10.0,9.130000,6.650000,90.0,4.63,100.0,0.0,0.0,1.0,...,0.0,15.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,92.0,10.0,9.240000,6.220000,89.0,6.17,100.0,0.0,0.0,1.0,...,0.0,20.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8922,73.0,10.0,28.049999,27.510000,37.0,0.89,32.0,0.0,0.0,1.0,...,23.0,35.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
8923,78.0,10.0,27.170000,27.040001,41.0,1.54,0.0,0.0,0.0,0.0,...,23.0,40.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
8924,78.0,10.0,27.120001,27.000000,41.0,1.54,0.0,0.0,0.0,0.0,...,23.0,45.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
8925,78.0,10.0,26.770000,26.790001,42.0,1.54,0.0,0.0,0.0,0.0,...,23.0,50.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
8926,81.0,10.0,26.670000,26.719999,42.0,1.54,0.0,0.0,0.0,0.0,...,23.0,55.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [7]:
transformed_df.columns

Index(['currentSpeed', 'visibility', 'temperature', 'FeelsLike', 'humidity',
       'windSpeed', 'cloudsAll', 'rain1h', 'snow1h', 'cloudy', 'clear',
       'atmosphere', 'snowy', 'rainy', 'Hour', 'Minute', 'May', 'Friday',
       'Monday', 'Saturday', 'Sunday', 'Thursday', 'Tuesday', 'Wednesday'],
      dtype='object')

In [8]:
transformed_df.rename({
    'visibility': "Visibility",
    'temperature': "Temperature",
    'FeelsLike': "Feels Like",
    'humidity':"Humidity",
    'windSpeed': "Wind Speed",
    'cloudsAll': "Clouds All",
    'rain1h': "Rain (1h)",
    'snow1h': "Snow (1h)",
    'cloudy':"Cloudy",
    'clear':"Clear",
    'atmosphere':"Atmosphere",
    'snowy': "Snowy",
    'rainy':"Rainy",
}, axis=1, inplace=True)
transformed_df

,currentSpeed,Visibility,Temperature,Feels Like,Humidity,Wind Speed,Clouds All,Rain (1h),Snow (1h),Cloudy,...,Hour,Minute,May,Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday
0,86.0,10.0,9.190000,6.730000,90.0,4.63,100.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,92.0,10.0,9.120000,6.640000,90.0,4.63,100.0,0.0,0.0,1.0,...,0.0,5.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,92.0,10.0,9.120000,6.640000,90.0,4.63,100.0,0.0,0.0,1.0,...,0.0,10.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,92.0,10.0,9.130000,6.650000,90.0,4.63,100.0,0.0,0.0,1.0,...,0.0,15.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,92.0,10.0,9.240000,6.220000,89.0,6.17,100.0,0.0,0.0,1.0,...,0.0,20.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8922,73.0,10.0,28.049999,27.510000,37.0,0.89,32.0,0.0,0.0,1.0,...,23.0,35.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
8923,78.0,10.0,27.170000,27.040001,41.0,1.54,0.0,0.0,0.0,0.0,...,23.0,40.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
8924,78.0,10.0,27.120001,27.000000,41.0,1.54,0.0,0.0,0.0,0.0,...,23.0,45.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
8925,78.0,10.0,26.770000,26.790001,42.0,1.54,0.0,0.0,0.0,0.0,...,23.0,50.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
8926,81.0,10.0,26.670000,26.719999,42.0,1.54,0.0,0.0,0.0,0.0,...,23.0,55.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [9]:
transformed_df.to_csv("./data/202305_gardiner_flow_weather.csv.zip", index=False, compression="zip")